config/routes.rb
Rails.application.routes.draw do
  resources :staffs
  resources :candidates do
    resources :progressions
  end
  resources :calendars
  resources :statistics


  # get  'candidates/:candidate_id/newProgression' , to: 'candidates#newProgression' , as: 'newProgression'
  # post 'candidates/:candidate_id/newProgression' , to: 'candidates#createProgression'

  # post 'progression' , to: 'candidates#newProgression'

  root 'candidates#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :calendars
  has_many :progressions
  has_many :candidates, :through =>  :calendars

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :gender, presence: true
  validates :phone, presence: true
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name , :email , :gender , :phone , :position)
    end
end

app/views/staffs/_form.html.erb
<%= form_for(staff) do |f| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <table class="table" style="margin-top: 30px">
        <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
          <th><%= f.text_field :name, {class: 'form-control' ,
                                       :style => "max-width: 340px;"} %></th>
        </tr>
        <tr>
          <th>E-mail</th>
          <th colspan="3"></th>
          <th><%= f.email_field :email, {class: 'form-control' ,
                                         :style => "max-width: 340px;"} %></th>
        </tr>
        <tr>
          <th>Gender</th>
          <th colspan="3"></th>
          <th><%= f.radio_button :gender, 'male', :checked => true , :style => "margin-left: 10px;" %>
            <%= label :gender_male, 'Male' %>
            <%= f.radio_button :gender, 'female', :style => "margin-left: 20px;" %>
            <%= label :gender_female, 'Female' %></th>
        </tr>
        <tr>
          <th>Phone No.</th>
          <th colspan="3"></th>
          <th><%= f.telephone_field :phone, {class: 'form-control' , :style => "max-width: 340px;"} %></th>
        </tr>
        <tr>
          <th>Position</th>
          <th colspan="3"></th>
          <th><%= f.select(:position, options_for_select([['Project Manager', 'Project Manager'],
                                                          ['Senier Programer', 'Senier Programer'],
                                                          ['Junior Programer', 'Junior Programer'],
                                                          ['Administrator', 'Administrator']]), {}, {class: "form-control" , :style => "max-width: 350px;"}) %>
          </th>
        </tr>
        </thead>
      </table>
    </div>

    <div class="actions">
      <div style="margin-bottom: 30px;">
        <%= f.submit "Submit", class: "btn btn-primary" %>
        <%= link_to 'Back', staffs_path , class: "btn btn-info" %>
      </div>
    </div>

<% end %>

app/views/staffs/edit.html.erb
<h1 align="center">Editing Staff</h1>

<%= render 'form', staff: @staff %>

app/views/staffs/index.html.erb
<h1 align="center">Staffs</h1>

<%= link_to 'New Staff', new_staff_path , class: "btn btn-secondary" %><br>

<table class="table" style="margin-top: 30px">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
      <th>Phone No.</th>
      <th colspan="3"></th>
      <th>E-mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= link_to staff.name , staff %></td>
        <th colspan="3"></th>
        <td><%= staff.phone %></td>
        <th colspan="3"></th>
        <td><%= staff.email %></td>
        <th colspan="3"></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/staffs/new.html.erb
<h1 align="center">New Staff</h1>

<%= render 'form', staff: @staff %>

app/views/staffs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @staff.name %><br>
  <strong>E-mail:</strong>
  <%= @staff.email %><br>
  <strong>Gender:</strong>
  <%= @staff.gender %><br>
  <strong>Phone:</strong>
  <%= @staff.phone %><br>
  <strong>Position:</strong>
  <%= @staff.position %><br>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) , class: "btn btn-primary" %>
<%= link_to 'Back', staffs_path , class: "btn btn-info" %>