config/routes.rb
Rails.application.routes.draw do
  resources :staffs
  resources :candidates do
    resources :progressions
  end
  resources :calendars
  resources :statistics


  # get  'candidates/:candidate_id/newProgression' , to: 'candidates#newProgression' , as: 'newProgression'
  # post 'candidates/:candidate_id/newProgression' , to: 'candidates#createProgression'

  # post 'progression' , to: 'candidates#newProgression'

  root 'candidates#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :progressions , dependent: :destroy
  has_many :calendars , dependent: :destroy
  has_many :staffs, :through =>  :calendars
  # has_many :calendars

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :gender, presence: true
  validates :phone, presence: true
  validates :address, presence: true, length: { maximum: 255 }

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @progression = @candidate.progressions.last
    @calendar = @candidate.calendars.last
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)
    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name ,:email ,:gender ,:phone ,
                                        :address ,:source ,:source_detail ,:position ,
                                        :pre_salary ,:expect_salary ,:blacklist,
                                        :test_general,:test_techtical)
    end

  # Never trust parameters from the scary internet, only allow the white list through.
  # def progression_params
  #     params.require(:progression).permit(:status , :staff_id)
  # end
end

app/views/candidates/_form.html.erb
<%= form_for(candidate) do |f| %>
    <% if candidate.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

          <ul>
            <% candidate.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

      <div class="field">
        <table class="table" style="margin-top: 30px">
          <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
            <th><%= f.text_field :name, {class: 'form-control' ,
                                         :style => "max-width: 340px;"} %></th>
          </tr>
          <tr>
            <th>E-mail</th>
            <th colspan="3"></th>
            <th><%= f.email_field :email, {class: 'form-control' ,
                                           :style => "max-width: 340px;"} %></th>
          </tr>
          <tr>
            <th>Gender</th>
            <th colspan="3"></th>
            <th><%= f.radio_button :gender, 'male', :checked => true , :style => "margin-left: 10px;" %>
              <%= label :gender_male, 'Male' %>
              <%= f.radio_button :gender, 'female', :style => "margin-left: 20px;" %>
              <%= label :gender_female, 'Female' %></th>
          </tr>
          <tr>
            <th>Address</th>
            <th colspan="3"></th>
            <th><%= f.text_area :address, {class: 'form-control' ,
                                                            :style => "max-width: 340px;"} %></th>
          </tr>
          <tr>
            <th>Phone No.</th>
            <th colspan="3"></th>
            <th><%= f.telephone_field :phone, {class: 'form-control' , :style => "max-width: 340px;"} %></th>
          </tr>
          <tr>
            <th>
              <div style="margin-bottom: 45px;">Source</div>
              <div>Detail</div>
            </th>
            <th colspan="3"></th>
            <th><%= f.select(:source, options_for_select([['Class', 'Class'], ['Web', 'Web']]),
                                     {}, {class: "form-control" , :style => "max-width: 200px;"}) %>
              <br>
              <%= f.text_field :source_detail, {class: 'form-control' , :style => "max-width: 340px;"} %>
            </th>
          </tr>
          <tr>
            <th>Position</th>
            <th colspan="3"></th>
            <th><%= f.select(:position, options_for_select([['Project Manager', 'Project Manager'],
                                                            ['Senier Programer', 'Senier Programer'],
                                                            ['Junior Programer', 'Junior Programer'],
                                                            ['Administrator', 'Administrator']]), {}, {class: "form-control" , :style => "max-width: 350px;"}) %>
            </th>
          </tr>
          <tr>
            <th>
              <div style="margin-bottom: 45px;">Pre-Salary</div>
              <div>Expecting-Salary</div>
            </th>
            <th colspan="3"></th>
            <th>
              <%= f.number_field :pre_salary, {class: 'form-control' , :style => "max-width: 300px;"} %>
              <br>
              <%= f.number_field :expect_salary, {class: 'form-control' , :style => "max-width: 300px;"} %>
            </th>
          </tr>
          <tr>
            <th>
              <div style="margin-bottom: 45px;">General Score</div>
              <div>Techtical Score</div>
            </th>
            <th colspan="3"></th>
            <th>
              <%= f.number_field :test_general, {class: 'form-control' , :style => "max-width: 200px;"} %>
              <br>
              <%= f.number_field :test_techtical, {class: 'form-control' , :style => "max-width: 200px;"} %>
            </th>
          </tr>
          <tr>
            <th>Blacklist</th>
            <th colspan="3"></th>
            <th><%= f.check_box :blacklist %></th>
          </tr>
          </thead>
        </table>
      </div>

    <div class="actions">
      <div style="margin-bottom: 30px;">
        <%= f.submit "Submit", class: "btn btn-primary" %>
        <%= link_to 'Back', candidates_path , class: "btn btn-info" %>
      </div>
    </div>

<% end %>

app/views/candidates/edit.html.erb
<h1 align="center">Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1 align="center">Candidates</h1>

<%= link_to 'New Candidate', new_candidate_path , class: "btn btn-secondary" %><br>

<table class="table" style="margin-top: 30px">
  <thead>
    <tr>
      <th id="items30">Name</th>
      <th colspan="5"></th>
      <th id="items30">Progression</th>
      <th colspan="5"></th>
      <th id="items30">Up coming schedule</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>

  <!-- PROGRESSION BAR -->
  <% if !candidate.progressions.last.nil? %>
       <% if candidate.progressions.last.status == "Contract[1]" %>
      <% a = 10 %>
          <% elsif candidate.progressions.last.status == "Interview[1]" %>
          <% a = 20 %>
              <% elsif candidate.progressions.last.status == "Estimate[1]" %>
          <% a = 30 %>
                  <% elsif candidate.progressions.last.status == "Contract[2]" %>
          <% a = 40 %>
                      <% elsif candidate.progressions.last.status == "Interview[2]" %>
          <% a = 50 %>
                          <% elsif candidate.progressions.last.status == "Estimate[2]" %>
          <% a = 60 %>
                              <% elsif candidate.progressions.last.status == "Contract[3]" %>
          <% a = 70 %>
                                  <% elsif candidate.progressions.last.status == "Contract[1]" %>
          <% a = 80 %>
                                      <% elsif candidate.progressions.last.status == "Sign Contract" %>
          <% a = 90 %>
                                          <% elsif candidate.progressions.last.status == "Pass" %>
          <% a = 100 %>
                                              <% elsif candidate.progressions.last.status == "Reject" %>
                                                  <% a = 0 %>
                                                  <% end %>
  <% end %>
  <!-- PROGRESSION BAR END -->

      <tr>
        <td><%= link_to candidate.name , candidate %></td>
        <th colspan="5"></th>
          <% if !candidate.progressions.last.nil? %>
            <td><%= link_to candidate.progressions.last.status ,edit_candidate_progression_path(candidate , candidate.progressions.last.id) %><br>
              <progress class="progress" value="<%= a %>" max="100" aria-describedby="example-caption-1"></progress>
            </td>
            <th colspan="5"></th>
      <% else %>
            <td>
              <%= link_to '-', new_candidate_progression_path(candidate) %><br>
              <progress class="progress" value="<%= a %>" max="100" aria-describedby="example-caption-1"></progress>
            </td>
            <th colspan="5"></th>
      <% end %>
        <% if !candidate.calendars.last.nil? %>
            <td><%= candidate.calendars.last.event %><br>
                <%= candidate.calendars.last.event_date.strftime("%Y-%m-%d") %>
            </td>
            <th colspan="5"></th>
        <% else %>
            <td><%= '-' %></td>
            <th colspan="5"></th>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/candidates/new.html.erb
<h1 align="center">New Candidate</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @candidate.name %><br>
  <strong>E-mail:</strong>
  <%= @candidate.email %><br>
  <strong>Phone:</strong>
  <%= @candidate.phone %><br>
  <strong>Address:</strong>
  <%= @candidate.address %><br>
  <strong>Source:</strong>
  <%= @candidate.source %> : <%= @candidate.source_detail %><br>
  <strong>Position:</strong>
  <%= @candidate.position %><br>
  <strong>General Test:</strong>
  <%= @candidate.test_general %><br>
  <strong>Technical Test:</strong>
  <%= @candidate.test_techtical %><br>

</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) , class: "btn btn-primary" %>
<%= link_to 'Back', candidates_path , class: "btn btn-info" %>