config/routes.rb
Rails.application.routes.draw do
  resources :staffs
  resources :candidates do
    resources :progressions
  end
  resources :calendars
  resources :statistics


  # get  'candidates/:candidate_id/newProgression' , to: 'candidates#newProgression' , as: 'newProgression'
  # post 'candidates/:candidate_id/newProgression' , to: 'candidates#createProgression'

  # post 'progression' , to: 'candidates#newProgression'

  root 'candidates#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :candidate
  belongs_to :staff

  validates :event,  presence: true, length: { maximum: 255 }
  validates :event_date,  presence: true, length: { maximum: 255 }
  validates :period,  presence: true, length: { maximum: 255 }
  validates :candidate_id,  presence: true, length: { maximum: 255 }
  validates :staff_id,  presence: true, length: { maximum: 255 }

  validate :calendar_check

  def calendar_check
    Calendar.where(event_date: event_date).each do |i|
        if(i.period == period && i.event != event)
          errors.add(:event_date, "Schedule is already full")
        end
      end
    Calendar.where(event_date: event_date).each do |i|
      if(i.period == period && i.staff_id == staff_id)
          errors.add(:event_date, "Schedule is already full")
      end
    end
   end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all
  end

  def front
    @calendars = Calendar.all
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to calendars_path, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:event , :event_date , :staff_id , :candidate_id , :period)
    end

end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_for(calendar) do |f| %>

    <% if calendar.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this candidate from being saved:</h2>

          <ul>
            <% calendar.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <table class="table" style="margin-top: 30px">
        <thead>
        <tr>
          <th>
            <div style="margin-bottom: 20px">Event</div>
          </th>
          <th colspan="3"></th>
          <th>
            <%= f.text_field :event , {class: "form-control" , :style => "max-width: 300px; margin-top: 10px"} %><br>
          </th>
        </tr>
        <tr>
          <th>Date</th>
          <th colspan="3"></th>
          <th>
            <%= f.date_field :event_date , {class: "form-control" , :style => "max-width: 300px;"} %>
          </th>
        </tr>
        <tr>
          <th>Period</th>
          <th colspan="3"></th>
          <th>
            <%= f.select(:period, options_for_select([['AM', 'AM'], ['PM', 'PM']]),
                         {}, {class: "form-control" , :style => "max-width: 300px;"}) %>
          </th>
        </tr>
        <tr>
          <th>Candidate</th>
          <th colspan="3"></th>
          <th>
            <%= f.select(:candidate_id, options_for_select(Candidate.all.collect { |p| [ p.name, p.id ] }),
                         {},  {class: "form-control" , :style => "max-width: 300px;"}) %>
          </th>
        </tr>
        <tr>
          <th>Staff</th>
          <th colspan="3"></th>
          <th>
            <%= f.select(:staff_id, options_for_select(Staff.all.collect { |p| [ p.name, p.id ] }),
                         {},  {class: "form-control" , :style => "max-width: 300px;"}) %>      </th>
        </tr>
        </thead>
      </table>
    </div>

    <div class="actions">
      <div style="margin-bottom: 30px;">
        <%= f.submit "Submit", class: "btn btn-primary" %>
        <%= link_to 'Back', calendars_path , class: "btn btn-info" %>
      </div>
    </div>

<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<h1 align="center">Calendars</h1>

<br>

<%= link_to 'New Event', new_calendar_path , class: "btn btn-secondary" %><br>

<br>

<%= month_calendar do |date| %>
    <div align="center"><strong><%= date.strftime("%d") %></strong><br></div>
    <% a = '1@#$%' %> <!--EVENT-->
    <% b = '1@#$%' %> <!--AM-->
    <% c = '1@#$%' %> <!--PM-->

    <% @calendars.each do |calendar| %>
        <% if calendar.event_date.strftime("%Y-%m-%d") == date.strftime("%Y-%m-%d") %>

            <!--SHOW AM+EVENT-->
            <% if calendar.period == "AM" %>
                <% if a != calendar.period + " : " + calendar.event %>
                    <% a = calendar.period + " : " + calendar.event %>
                    <strong><%= a %></strong><br>
                    c : <%= Candidate.find(calendar.candidate_id).name %>
                <% end %>
                <br>s :
                <% if b != Staff.find(calendar.staff_id).name %>
                    <% b = Staff.find(calendar.staff_id).name %>
                    <%= b %>
                <% end %>
            <% end %>

            <!--SHOW PM+EVENT-->
            <% if calendar.period == "PM" %>
                <% if a != calendar.period + " : " + calendar.event %>
                    <% a = calendar.period + " : " + calendar.event %>
                    <br><strong><%= a %></strong><br>
                    c : <%= Candidate.find(calendar.candidate_id).name %>
                <% end %>
                <br>s :
                <% if c != Staff.find(calendar.staff_id).name %>
                    <% c = Staff.find(calendar.staff_id).name %>
                    <%= c + " " %>
                <% end %>
            <% end %>

        <% end %>
    <% end %>
<% end %>

app/views/calendars/new.html.erb
<h1 align="center">New Event</h1>

<%= render 'form', calendar: @calendar %>

app/views/calendars/show.html.erb
<p>
  <strong>Event:</strong>
  <%= @calendar.event %>
</p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>