config/routes.rb
Rails.application.routes.draw do
  resources :staffs
  resources :candidates do
    resources :progressions
  end
  resources :calendars
  resources :statistics


  # get  'candidates/:candidate_id/newProgression' , to: 'candidates#newProgression' , as: 'newProgression'
  # post 'candidates/:candidate_id/newProgression' , to: 'candidates#createProgression'

  # post 'progression' , to: 'candidates#newProgression'

  root 'candidates#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-dark bg-inverse">
  <a class="navbar-brand" href="#">ARMS</a>
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <a <%= link_to "Candidate", candidates_path , :class => "nav-link" %> </a>
    </li>
    <li class="nav-item">
      <a <%= link_to "Staff", staffs_path , :class => "nav-link" %></a>
    </li>
    <li class="nav-item">
      <a <%= link_to "Calendar", calendars_path , :class => "nav-link" %></a>
    </li>
    <li class="nav-item">
      <a <%= link_to "Statistic", statistics_path , :class => "nav-link" %></a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagrant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container" style="margin-top: 40px">
    <%= yield %>
  </div>
  </body>
</html>